unit UDmReports;

interface

uses
  System.SysUtils, System.Classes, Data.DB, ppParameter, ppDesignLayer, ppProd,
  ppClass, ppReport, ppComm, ppRelatv, ppDB, ppDBPipe, ppStrtch, ppMemo,
  ppCtrls, Vcl.Imaging.pngimage, ppPrnabl, ppBands, ppCache, ppVar,
  FireDAC.Stan.Intf, FireDAC.Stan.Option, FireDAC.Stan.Param,
  FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf, FireDAC.DApt.Intf,
  FireDAC.Stan.Async, FireDAC.DApt, FireDAC.Comp.DataSet, FireDAC.Comp.Client,FMX.Dialogs,
  Vcl.Imaging.jpeg;

type
  TdmReport = class(TDataModule)
    ppDBPedido: TppDBPipeline;
    ppRepPedido: TppReport;
    ppDesignLayers1: TppDesignLayers;
    ppDesignLayer1: TppDesignLayer;
    ppParameterList1: TppParameterList;
    DBPedidoItens: TppDBPipeline;
    DBPedidoHist: TppDBPipeline;
    dsPedido: TDataSource;
    dsIntems: TDataSource;
    dsHist: TDataSource;
    ppHeaderBand1: TppHeaderBand;
    ppDetailBand1: TppDetailBand;
    ppFooterBand1: TppFooterBand;
    ppImage1: TppImage;
    ppLabel1: TppLabel;
    ppShape1: TppShape;
    ppLabel2: TppLabel;
    ppDBText1: TppDBText;
    ppLabel7: TppLabel;
    ppDBText6: TppDBText;
    ppLabel9: TppLabel;
    ppDBText8: TppDBText;
    ppLabel10: TppLabel;
    ppDBMemo1: TppDBMemo;
    ppLblTipoMaquina: TppLabel;
    ppDBLBLMaquina: TppDBMemo;
    ppLabel14: TppLabel;
    ppDBMemo3: TppDBMemo;
    ppDBLBLServico: TppDBText;
    pplblDescricao: TppLabel;
    ppDescricaoServico: TppDBText;
    ppLine1: TppLine;
    ppLabel3: TppLabel;
    ppDBText2: TppDBText;
    ppLabel4: TppLabel;
    ppDBText3: TppDBText;
    ppLabel5: TppLabel;
    ppDBText4: TppDBText;
    ppLabel6: TppLabel;
    ppLabel8: TppLabel;
    ppDBText7: TppDBText;
    ppLabel12: TppLabel;
    ppDBText10: TppDBText;
    ppLine2: TppLine;
    ppShape2: TppShape;
    ppDBCalc1: TppDBCalc;
    ppDBCalc4: TppDBCalc;
    ppSummaryBand1: TppSummaryBand;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppLine3: TppLine;
    ppDBText9: TppDBText;
    ppDBOrcamento: TppDBPipeline;
    ppRepOrcamento: TppReport;
    dsOrcamento: TDataSource;
    ppDBItensOrcamento: TppDBPipeline;
    dsItenOrcamento: TDataSource;
    ppParameterList2: TppParameterList;
    ppDesignLayers2: TppDesignLayers;
    ppDesignLayer2: TppDesignLayer;
    ppHeaderBand2: TppHeaderBand;
    ppDetailBand2: TppDetailBand;
    ppFooterBand2: TppFooterBand;
    ppShape3: TppShape;
    ppLblOrdemPedido: TppLabel;
    ppShape4: TppShape;
    ppLabel13: TppLabel;
    ppDBText5: TppDBText;
    ppLabel15: TppLabel;
    ppDBText11: TppDBText;
    ppLabel16: TppLabel;
    ppDBText12: TppDBText;
    ppLabel17: TppLabel;
    ppDBMemo2: TppDBMemo;
    ppLabel19: TppLabel;
    ppDBMemo5: TppDBMemo;
    ppLabel20: TppLabel;
    ppLine4: TppLine;
    ppLabel21: TppLabel;
    ppLabel22: TppLabel;
    ppLabel24: TppLabel;
    ppDBText13: TppDBText;
    ppDBText15: TppDBText;
    ppDBText16: TppDBText;
    ppLabel18: TppLabel;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppLine5: TppLine;
    ppSummaryBand2: TppSummaryBand;
    ppShape5: TppShape;
    ppDBCalc2: TppDBCalc;
    ppDBCalc3: TppDBCalc;
    ppSystemVariable3: TppSystemVariable;
    ppSystemVariable4: TppSystemVariable;
    ppLabel23: TppLabel;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppDBCalc5: TppDBCalc;
    ppLine6: TppLine;
    ppDBText14: TppDBText;
    qryComparativo: TFDQuery;
    dsComparativo: TDataSource;
    ppDBPRepComparativo: TppDBPipeline;
    ppRepComparativo: TppReport;
    ppParameterList3: TppParameterList;
    ppDesignLayers3: TppDesignLayers;
    ppDesignLayer3: TppDesignLayer;
    ppHeaderBand3: TppHeaderBand;
    ppDetailBand3: TppDetailBand;
    ppFooterBand3: TppFooterBand;
    qryDadosOrcamento: TFDQuery;
    ppShape27: TppShape;
    ppLabel48: TppLabel;
    ppLabel49: TppLabel;
    ppLabel50: TppLabel;
    ppLabel51: TppLabel;
    ppLabel52: TppLabel;
    ppImage3: TppImage;
    qryDadosPedido: TFDQuery;
    ppLine7: TppLine;
    ppSystemVariable5: TppSystemVariable;
    ppSystemVariable6: TppSystemVariable;
    ppShape6: TppShape;
    ppLabel26: TppLabel;
    ppLabel25: TppLabel;
    ppLabel31: TppLabel;
    ppDBMemo6: TppDBMemo;
    ppLabel35: TppLabel;
    ppDBText21: TppDBText;
    ppLabel36: TppLabel;
    ppDBText22: TppDBText;
    ppLabel37: TppLabel;
    ppDBText23: TppDBText;
    ppLabel11: TppLabel;
    ppDBText20: TppDBText;
    ppLabel29: TppLabel;
    ppDBText24: TppDBText;
    ExtratoCombustivel: TFDQuery;
    dsExtratoComb: TDataSource;
    ppReportExtratoComb: TppReport;
    ppHeaderBand4: TppHeaderBand;
    ppShape7: TppShape;
    ppLabel38: TppLabel;
    ppShape8: TppShape;
    ppLabel39: TppLabel;
    ppLabel40: TppLabel;
    ppLine8: TppLine;
    ppDetailBand4: TppDetailBand;
    ppLine9: TppLine;
    ppFooterBand4: TppFooterBand;
    ppSystemVariable7: TppSystemVariable;
    ppSystemVariable8: TppSystemVariable;
    ppLine10: TppLine;
    ppSummaryBand3: TppSummaryBand;
    ppDesignLayers4: TppDesignLayers;
    ppDesignLayer4: TppDesignLayer;
    ppParameterList4: TppParameterList;
    DBPExtratoComb: TppDBPipeline;
    ExtratoCombustiveldatadia: TDateField;
    ExtratoCombustivelsaldoinicial: TFMTBCDField;
    ExtratoCombustiveltotalentrada: TFMTBCDField;
    ExtratoCombustiveltotalsaida: TFMTBCDField;
    ExtratoCombustivelsaldodia: TFMTBCDField;
    ppImage2: TppImage;
    ppLblCombustivel: TppLabel;
    ppLblPeriodoComb: TppLabel;
    ppLabel41: TppLabel;
    ppDBText25: TppDBText;
    ppLabel42: TppLabel;
    ppDBText26: TppDBText;
    ppLabel43: TppLabel;
    ppDBText27: TppDBText;
    ppDBText28: TppDBText;
    ppDBText29: TppDBText;
    ppLabel53: TppLabel;
    ppLabel54: TppLabel;
    ExtratoBomba: TFDQuery;
    DateField1: TDateField;
    FMTBCDField1: TFMTBCDField;
    FMTBCDField2: TFMTBCDField;
    FMTBCDField3: TFMTBCDField;
    FMTBCDField4: TFMTBCDField;
    dsExtratoBomba: TDataSource;
    ppRepExtratoBomba: TppReport;
    ppHeaderBand5: TppHeaderBand;
    ppShape9: TppShape;
    ppLabel44: TppLabel;
    ppShape10: TppShape;
    ppLabel45: TppLabel;
    ppLabel55: TppLabel;
    ppLine11: TppLine;
    ppImage4: TppImage;
    LblBomba: TppLabel;
    ppLblPeriodoBomba: TppLabel;
    ppLabel58: TppLabel;
    ppLabel59: TppLabel;
    ppLabel60: TppLabel;
    ppLabel61: TppLabel;
    ppDetailBand5: TppDetailBand;
    ppLine12: TppLine;
    ppDBText30: TppDBText;
    ppDBText31: TppDBText;
    ppDBText32: TppDBText;
    ppDBText33: TppDBText;
    ppDBText34: TppDBText;
    ppFooterBand5: TppFooterBand;
    ppSystemVariable9: TppSystemVariable;
    ppSystemVariable10: TppSystemVariable;
    ppLine13: TppLine;
    ppSummaryBand4: TppSummaryBand;
    ppDesignLayers5: TppDesignLayers;
    ppDesignLayer5: TppDesignLayer;
    ppParameterList5: TppParameterList;
    ppDBExtratoBomba: TppDBPipeline;
    ExtratoBombatotalentradatransf: TFMTBCDField;
    ExtratoBombatotalsaidatransf: TFMTBCDField;
    ppLabel56: TppLabel;
    ppDBText35: TppDBText;
    ppLabel57: TppLabel;
    ppDBText36: TppDBText;
    ppLabel62: TppLabel;
    dsContratos: TDataSource;
    dsEmbarques: TDataSource;
    ppDBPContrato: TppDBPipeline;
    ppDBPEmbarque: TppDBPipeline;
    ppRepContratos: TppReport;
    ppHeaderBand6: TppHeaderBand;
    ppLabel63: TppLabel;
    ppShape12: TppShape;
    ppLabel64: TppLabel;
    ppLabel65: TppLabel;
    ppLine14: TppLine;
    ppImage5: TppImage;
    ppLabel68: TppLabel;
    ppLabel69: TppLabel;
    ppLabel70: TppLabel;
    ppLabel72: TppLabel;
    ppDetailBand6: TppDetailBand;
    ppDBText37: TppDBText;
    ppDBText38: TppDBText;
    ppDBText39: TppDBText;
    ppDBText43: TppDBText;
    ppFooterBand6: TppFooterBand;
    ppSystemVariable11: TppSystemVariable;
    ppSystemVariable12: TppSystemVariable;
    ppLine16: TppLine;
    ppSummaryBand5: TppSummaryBand;
    ppDesignLayers6: TppDesignLayers;
    ppDesignLayer6: TppDesignLayer;
    ppParameterList6: TppParameterList;
    ppDBText44: TppDBText;
    ppDBText45: TppDBText;
    ppDBText46: TppDBText;
    ppLabel66: TppLabel;
    ppLabel75: TppLabel;
    ppDBText47: TppDBText;
    ppLabel76: TppLabel;
    ppDBText48: TppDBText;
    ppLabel77: TppLabel;
    ppDBText49: TppDBText;
    ppLabel78: TppLabel;
    ppDBText50: TppDBText;
    ppLine17: TppLine;
    ppLabel79: TppLabel;
    ppDBText51: TppDBText;
    ppLabel80: TppLabel;
    ppDBText52: TppDBText;
    ppLabel81: TppLabel;
    ppDBText53: TppDBText;
    ppLine18: TppLine;
    ppLabel67: TppLabel;
    ppLabel73: TppLabel;
    ppLabel82: TppLabel;
    ppDBText42: TppDBText;
    ppDBText54: TppDBText;
    ppLabel71: TppLabel;
    ppLine19: TppLine;
    ppLabel74: TppLabel;
    ppLabel83: TppLabel;
    ppLabel84: TppLabel;
    ppLabel85: TppLabel;
    ppLabel86: TppLabel;
    ppShape14: TppShape;
    ppShape15: TppShape;
    ppShape16: TppShape;
    ppShape17: TppShape;
    ppShape18: TppShape;
    ppShape19: TppShape;
    ppDBText40: TppDBText;
    ppDBText41: TppDBText;
    ppShape21: TppShape;
    ppShape22: TppShape;
    ppDBText55: TppDBText;
    ppDBText56: TppDBText;
    ppShape23: TppShape;
    ppShape24: TppShape;
    ppDBText57: TppDBText;
    ppShape25: TppShape;
    ppDBText58: TppDBText;
    ppLabel87: TppLabel;
    ppLabel88: TppLabel;
    ppDBText59: TppDBText;
    ppLabel89: TppLabel;
    ppDBText60: TppDBText;
    ppLabel90: TppLabel;
    ppDBText61: TppDBText;
    SaldoAtualCombustivel: TFDQuery;
    SaldoAtualCombustivellocalestoque: TWideStringField;
    SaldoAtualCombustivelproduto: TWideStringField;
    SaldoAtualCombustivelentradas: TFMTBCDField;
    SaldoAtualCombustivelsaidas: TFMTBCDField;
    SaldoAtualCombustivelsaldo: TFMTBCDField;
    SaldoAtualCombustiveltotal_saida_trans: TFMTBCDField;
    SaldoAtualCombustiveltotal_entrada_trans: TFMTBCDField;
    dsSaldoAtual: TDataSource;
    ppDBSaldoAtual: TppDBPipeline;
    ppRepSaldoAtual: TppReport;
    ppHeaderBand7: TppHeaderBand;
    ppShape26: TppShape;
    ppLabel91: TppLabel;
    ppLine15: TppLine;
    ppImage6: TppImage;
    ppLabel96: TppLabel;
    ppLabel97: TppLabel;
    ppLabel98: TppLabel;
    ppLabel99: TppLabel;
    ppLabel100: TppLabel;
    ppDetailBand7: TppDetailBand;
    ppLine20: TppLine;
    ppDBText62: TppDBText;
    ppDBText63: TppDBText;
    ppDBText64: TppDBText;
    ppDBText65: TppDBText;
    ppDBText66: TppDBText;
    ppFooterBand7: TppFooterBand;
    ppSystemVariable13: TppSystemVariable;
    ppSystemVariable14: TppSystemVariable;
    ppSummaryBand6: TppSummaryBand;
    ppDesignLayers7: TppDesignLayers;
    ppDesignLayer7: TppDesignLayer;
    ppParameterList7: TppParameterList;
    ppLabel92: TppLabel;
    ppDBText67: TppDBText;
    ppLabel93: TppLabel;
    ppDBText68: TppDBText;
    ppLabel94: TppLabel;
    ppDBText69: TppDBText;
    ppLabel95: TppLabel;
    ppDBText70: TppDBText;
    ppLabel101: TppLabel;
    ppDBText71: TppDBText;
    ppLine21: TppLine;
    ppLabel102: TppLabel;
    ppDBText72: TppDBText;
    ppLabel103: TppLabel;
    ppShape28: TppShape;
    ppDBText73: TppDBText;
    ppShape11: TppShape;
    ExtratoDiaMaquina: TFDQuery;
    dsExtratoMaquinaDia: TDataSource;
    ppDBExtratoMaquinaDia: TppDBPipeline;
    ppRepExtratoMaquinaDia: TppReport;
    ppHeaderBand8: TppHeaderBand;
    ppLabel104: TppLabel;
    ppShape30: TppShape;
    ppLabel105: TppLabel;
    ppLabel106: TppLabel;
    ppLine22: TppLine;
    ppImage7: TppImage;
    ppLblPeriodoEx: TppLabel;
    ppDetailBand8: TppDetailBand;
    ppFooterBand8: TppFooterBand;
    ppSystemVariable15: TppSystemVariable;
    ppSystemVariable16: TppSystemVariable;
    ppLine24: TppLine;
    ppSummaryBand7: TppSummaryBand;
    ppDesignLayers8: TppDesignLayers;
    ppDesignLayer8: TppDesignLayer;
    ppParameterList8: TppParameterList;
    ppLabel116: TppLabel;
    ppDBMemo4: TppDBMemo;
    ppDBMemo7: TppDBMemo;
    ppDBText84: TppDBText;
    ppDBText86: TppDBText;
    ppShape34: TppShape;
    dsDadosOrcamentoComp: TDataSource;
    ppDBPOrcamentoComp: TppDBPipeline;
    qryDadosOrcamentoqtde: TIntegerField;
    qryDadosOrcamentocodigofabricante: TWideStringField;
    qryDadosOrcamentodescricao: TWideStringField;
    qryComparativoid: TIntegerField;
    qryComparativostatus: TIntegerField;
    qryComparativodatareg: TSQLTimeStampField;
    qryComparativoidusuario: TIntegerField;
    qryComparativodataalteracao: TSQLTimeStampField;
    qryComparativoidusuarioalteracao: TIntegerField;
    qryComparativoitem: TIntegerField;
    qryComparativoidproduto: TIntegerField;
    qryComparativoidpedido: TIntegerField;
    qryComparativoidfornecedor1: TIntegerField;
    qryComparativovlfornecedor1: TBCDField;
    qryComparativoidfornecedor2: TIntegerField;
    qryComparativovlfornecedor2: TBCDField;
    qryComparativoidfornecedor3: TIntegerField;
    qryComparativovlfornecedor3: TBCDField;
    qryComparativoidfornecedor4: TIntegerField;
    qryComparativovlfornecedor4: TBCDField;
    qryComparativoidfornecedor5: TIntegerField;
    qryComparativovlfornecedor5: TBCDField;
    qryComparativoqtde: TIntegerField;
    qryComparativoidentificador: TWideStringField;
    qryComparativodatapedido: TDateField;
    qryComparativosolicitante: TWideStringField;
    qryComparativoaplicacao: TWideMemoField;
    qryComparativoproduto: TWideStringField;
    qryComparativocodigofabricante: TWideStringField;
    qryComparativounidademedida: TWideStringField;
    qryComparativonomefornecedor1: TWideStringField;
    qryComparativonomefornecedor2: TWideStringField;
    qryComparativonomefornecedor3: TWideStringField;
    qryComparativonomefornecedor4: TWideStringField;
    qryComparativonomefornecedor5: TWideStringField;
    ppDBText76: TppDBText;
    ppDBText77: TppDBText;
    ppDBText78: TppDBText;
    ppDBMemo8: TppDBMemo;
    ppShape13: TppShape;
    ppLabel30: TppLabel;
    ppLabel32: TppLabel;
    ppLabel33: TppLabel;
    ppLabel34: TppLabel;
    ppLabel46: TppLabel;
    qryComparativoidorcamentoforn1: TIntegerField;
    qryComparativoidorcamentoforn2: TIntegerField;
    qryComparativoidorcamentoforn3: TIntegerField;
    qryComparativoidorcamentoforn4: TIntegerField;
    qryComparativoidorcamentoforn5: TIntegerField;
    qryComparativomarcaforn1: TWideStringField;
    qryComparativomarcaforn2: TWideStringField;
    qryComparativomarcaforn3: TWideStringField;
    qryComparativomarcaforn4: TWideStringField;
    qryComparativomarcaforn5: TWideStringField;
    ppDBText79: TppDBText;
    ppDBText80: TppDBText;
    ppDBText87: TppDBText;
    ppDBText88: TppDBText;
    ppDBText89: TppDBText;
    ppLabel132: TppLabel;
    ppLabel133: TppLabel;
    ppDBText94: TppDBText;
    ppLabel134: TppLabel;
    ppLabel120: TppLabel;
    ppLabel121: TppLabel;
    ppDBText90: TppDBText;
    ppLabel122: TppLabel;
    ppLabel123: TppLabel;
    ppLabel124: TppLabel;
    ppDBText91: TppDBText;
    ppLabel125: TppLabel;
    ppLabel126: TppLabel;
    ppLabel127: TppLabel;
    ppDBText92: TppDBText;
    ppLabel128: TppLabel;
    ppLabel135: TppLabel;
    ppLabel136: TppLabel;
    ppDBText95: TppDBText;
    ppLabel137: TppLabel;
    ppDBText93: TppDBText;
    ppDBText96: TppDBText;
    ppDBText97: TppDBText;
    ppDBText98: TppDBText;
    ppDBText99: TppDBText;
    ppDBText100: TppDBText;
    ppDBText101: TppDBText;
    ppDBText102: TppDBText;
    ppDBText103: TppDBText;
    ppDBText104: TppDBText;
    ppShape20: TppShape;
    ppShape35: TppShape;
    ppShape36: TppShape;
    ppShape37: TppShape;
    ppShape38: TppShape;
    qryComparativovalortotal_1: TFMTBCDField;
    qryComparativovalortotal_2: TFMTBCDField;
    qryComparativovalortotal_3: TFMTBCDField;
    qryComparativovalortotal_4: TFMTBCDField;
    qryComparativovalortotal_5: TFMTBCDField;
    ppDBText105: TppDBText;
    ppDBText106: TppDBText;
    ppDBText107: TppDBText;
    ppDBText108: TppDBText;
    ppDBText109: TppDBText;
    ppLine23: TppLine;
    ppShape39: TppShape;
    ppShape40: TppShape;
    ppShape41: TppShape;
    ppShape42: TppShape;
    ppShape43: TppShape;
    qryComparativofreteforn1: TFMTBCDField;
    qryComparativofreteforn2: TFMTBCDField;
    qryComparativofreteforn3: TFMTBCDField;
    qryComparativofreteforn4: TFMTBCDField;
    qryComparativofreteforn5: TFMTBCDField;
    qryComparativoicmstforn1: TFMTBCDField;
    qryComparativoicmstforn2: TFMTBCDField;
    qryComparativoicmstforn3: TFMTBCDField;
    qryComparativoicmstforn4: TFMTBCDField;
    qryComparativoicmstforn5: TFMTBCDField;
    qryComparativodescontoforn1: TFMTBCDField;
    qryComparativodescontoforn2: TFMTBCDField;
    qryComparativodescontoforn3: TFMTBCDField;
    qryComparativodescontoforn4: TFMTBCDField;
    qryComparativodescontoforn5: TFMTBCDField;
    qryComparativovalortotaldesconto_1: TFMTBCDField;
    qryComparativovalortotaldesconto_2: TFMTBCDField;
    qryComparativovalortotaldesconto_3: TFMTBCDField;
    qryComparativovalortotaldesconto_4: TFMTBCDField;
    qryComparativovalortotaldesconto_5: TFMTBCDField;
    ppSummaryBand8: TppSummaryBand;
    ppShape53: TppShape;
    ppShape52: TppShape;
    ppShape51: TppShape;
    ppShape50: TppShape;
    ppShape49: TppShape;
    ppDBCalc7: TppDBCalc;
    ppDBCalc8: TppDBCalc;
    ppDBCalc9: TppDBCalc;
    ppDBCalc10: TppDBCalc;
    ppDBCalc11: TppDBCalc;
    ppShape44: TppShape;
    ppShape45: TppShape;
    ppShape46: TppShape;
    ppShape47: TppShape;
    ppShape48: TppShape;
    ppLabel47: TppLabel;
    ppLabel115: TppLabel;
    ppDBCalc12: TppDBCalc;
    ppDBCalc13: TppDBCalc;
    ppDBCalc14: TppDBCalc;
    ppDBCalc15: TppDBCalc;
    ppDBCalc16: TppDBCalc;
    ppShape54: TppShape;
    ppShape55: TppShape;
    ppShape56: TppShape;
    ppShape57: TppShape;
    ppShape58: TppShape;
    ppLabel117: TppLabel;
    ppDBCalc17: TppDBCalc;
    ppDBCalc18: TppDBCalc;
    ppDBCalc19: TppDBCalc;
    ppDBCalc20: TppDBCalc;
    ppDBCalc21: TppDBCalc;
    ppShape59: TppShape;
    ppShape60: TppShape;
    ppShape61: TppShape;
    ppShape62: TppShape;
    ppShape63: TppShape;
    ppLabel118: TppLabel;
    ppDBCalc22: TppDBCalc;
    ppDBCalc23: TppDBCalc;
    ppDBCalc24: TppDBCalc;
    ppDBCalc25: TppDBCalc;
    ppDBCalc26: TppDBCalc;
    ppShape64: TppShape;
    ppShape65: TppShape;
    ppShape66: TppShape;
    ppShape67: TppShape;
    ppShape68: TppShape;
    ppLabel119: TppLabel;
    ppDBCalc27: TppDBCalc;
    ppDBCalc28: TppDBCalc;
    ppDBCalc29: TppDBCalc;
    ppDBCalc30: TppDBCalc;
    ppDBCalc31: TppDBCalc;
    qryAux: TFDQuery;
    ExtratoDiaMaquinabomba: TWideStringField;
    ExtratoDiaMaquinacombustivel: TWideStringField;
    ExtratoDiaMaquinadatadia: TDateField;
    ExtratoDiaMaquinasaldoinicial: TBCDField;
    ExtratoDiaMaquinatotalentrada: TBCDField;
    ExtratoDiaMaquinatotalsaida: TBCDField;
    ExtratoDiaMaquinatotalsaidatrnasf: TBCDField;
    ExtratoDiaMaquinamaquina: TWideStringField;
    ExtratoDiaMaquinasaidaabastecimento: TBCDField;
    ExtratoDiaMaquinasaldodia: TBCDField;
    ppDBText81: TppDBText;
    ppDBText82: TppDBText;
    ppDBText83: TppDBText;
    ppDBText74: TppDBText;
    ppDBText75: TppDBText;
    ppDBText85: TppDBText;
    ppShape29: TppShape;
    ppLabel109: TppLabel;
    ppLabel110: TppLabel;
    ppLabel111: TppLabel;
    ppLabel108: TppLabel;
    ppLabel112: TppLabel;
    ppLabel107: TppLabel;
    ppLabel113: TppLabel;
    ppLabel114: TppLabel;
    dsListaEntNotas: TDataSource;
    ppDBPListaEntNotas: TppDBPipeline;
    ppDBPListaEntNotasppField1: TppField;
    ppDBPListaEntNotasppField2: TppField;
    ppDBPListaEntNotasppField3: TppField;
    ppDBPListaEntNotasppField4: TppField;
    ppDBPListaEntNotasppField5: TppField;
    ppDBPListaEntNotasppField6: TppField;
    ppDBPListaEntNotasppField7: TppField;
    ppDBPListaEntNotasppField8: TppField;
    ppDBPListaEntNotasppField9: TppField;
    ppDBPListaEntNotasppField10: TppField;
    ppDBPListaEntNotasppField11: TppField;
    ppDBPListaEntNotasppField12: TppField;
    ppDBPListaEntNotasppField13: TppField;
    ppDBPListaEntNotasppField14: TppField;
    ppDBPListaEntNotasppField15: TppField;
    ppDBPListaEntNotasppField16: TppField;
    ppDBPListaEntNotasppField17: TppField;
    ppDBPListaEntNotasppField18: TppField;
    ppDBPListaEntNotasppField19: TppField;
    ppDBPListaEntNotasppField20: TppField;
    ppDBPListaEntNotasppField21: TppField;
    ppDBPListaEntNotasppField22: TppField;
    ppDBPListaEntNotasppField23: TppField;
    ppDBPListaEntNotasppField24: TppField;
    ppDBPListaEntNotasppField25: TppField;
    ppDBPListaEntNotasppField26: TppField;
    ppRepListaEntNotas: TppReport;
    ppHeaderBand13: TppHeaderBand;
    ppShape90: TppShape;
    ppLabel182: TppLabel;
    ppImage12: TppImage;
    ppShape89: TppShape;
    ppLabel183: TppLabel;
    ppLabel187: TppLabel;
    ppLabel188: TppLabel;
    ppLabel189: TppLabel;
    ppDBText155: TppDBText;
    ppLabel191: TppLabel;
    ppLabel192: TppLabel;
    ppLabel193: TppLabel;
    ppLabel194: TppLabel;
    ppDBText145: TppDBText;
    ppLabel195: TppLabel;
    ppDBText156: TppDBText;
    ppDBText157: TppDBText;
    ppLabel196: TppLabel;
    ppLabel190: TppLabel;
    ppDetailBand13: TppDetailBand;
    ppLine35: TppLine;
    ppDBText148: TppDBText;
    ppDBText149: TppDBText;
    ppDBText150: TppDBText;
    ppDBText152: TppDBText;
    ppDBText153: TppDBText;
    ppDBText154: TppDBText;
    ppDBText146: TppDBText;
    ppFooterBand13: TppFooterBand;
    ppSystemVariable25: TppSystemVariable;
    ppSystemVariable26: TppSystemVariable;
    ppLine34: TppLine;
    ppSummaryBand13: TppSummaryBand;
    ppShape91: TppShape;
    ppDBCalc38: TppDBCalc;
    ppDBCalc39: TppDBCalc;
    ppLabel184: TppLabel;
    ppDBCalc40: TppDBCalc;
    ppLabel185: TppLabel;
    ppLabel186: TppLabel;
    ppDesignLayers13: TppDesignLayers;
    ppDesignLayer13: TppDesignLayer;
    ppParameterList13: TppParameterList;
    qryImprimeNota: TFDQuery;
    qryImprimeNotafornecedor: TWideStringField;
    qryImprimeNotadataentradaestoque: TDateField;
    qryImprimeNotanumeronf: TIntegerField;
    qryImprimeNotadataemissao: TDateField;
    qryImprimeNotadataentradaestoque_1: TDateField;
    qryImprimeNotaproduto: TWideStringField;
    qryImprimeNotalocalestoque: TWideStringField;
    qryImprimeNotacentrocusto: TWideStringField;
    qryImprimeNotaid: TIntegerField;
    qryImprimeNotastatus: TIntegerField;
    qryImprimeNotadatareg: TSQLTimeStampField;
    qryImprimeNotaidusuario: TIntegerField;
    qryImprimeNotadataalteracao: TSQLTimeStampField;
    qryImprimeNotaidusuarioalteracao: TIntegerField;
    qryImprimeNotaidnota: TIntegerField;
    qryImprimeNotaidproduto: TIntegerField;
    qryImprimeNotavalortotalnf: TFMTBCDField;
    qryImprimeNotaqtditens: TFMTBCDField;
    qryImprimeNotaunidademedida: TWideStringField;
    qryImprimeNotapesoembalagem: TFMTBCDField;
    qryImprimeNotaidlocalestoque: TIntegerField;
    qryImprimeNotasyncaws: TIntegerField;
    qryImprimeNotasyncfaz: TIntegerField;
    qryImprimeNotavaloruni: TFMTBCDField;
    qryImprimeNotatipo: TWideStringField;
    qryImprimeNotaitem: TLargeintField;
    QryEstoqueG: TFDQuery;
    QryEstoqueGnome: TWideStringField;
    QryEstoqueGcodigofabricante: TWideStringField;
    QryEstoqueGtotalentradas: TFMTBCDField;
    QryEstoqueGtotalsaida: TFMTBCDField;
    QryEstoqueGsaldoatual: TBCDField;
    QryEstoqueGcustomedio: TBCDField;
    QryEstoqueGultimaentrada: TDateField;
    QryEstoqueGultimasaida: TDateField;
    dsEstoqueG: TDataSource;
    ppDBEstoqueG: TppDBPipeline;
    ppDBEstoqueGppField1: TppField;
    ppDBEstoqueGppField2: TppField;
    ppDBEstoqueGppField3: TppField;
    ppDBEstoqueGppField4: TppField;
    ppDBEstoqueGppField5: TppField;
    ppDBEstoqueGppField6: TppField;
    ppDBEstoqueGppField7: TppField;
    ppDBEstoqueGppField8: TppField;
    ppRepEstoqueG: TppReport;
    ppHeaderBand10: TppHeaderBand;
    ppShape78: TppShape;
    ppLabel149: TppLabel;
    ppLine28: TppLine;
    ppImage9: TppImage;
    ppLabel150: TppLabel;
    ppLabel151: TppLabel;
    ppLabel152: TppLabel;
    ppLabel153: TppLabel;
    ppLabel154: TppLabel;
    ppLabel155: TppLabel;
    ppLabel156: TppLabel;
    ppLabel181: TppLabel;
    ppDetailBand10: TppDetailBand;
    ppLine29: TppLine;
    ppDBText118: TppDBText;
    ppDBText119: TppDBText;
    ppDBText120: TppDBText;
    ppDBText121: TppDBText;
    ppDBText122: TppDBText;
    ppDBText123: TppDBText;
    ppDBText117: TppDBText;
    ppDBText144: TppDBText;
    ppFooterBand10: TppFooterBand;
    ppSystemVariable19: TppSystemVariable;
    ppSystemVariable20: TppSystemVariable;
    ppSummaryBand10: TppSummaryBand;
    ppDesignLayers10: TppDesignLayers;
    ppDesignLayer10: TppDesignLayer;
    ppParameterList10: TppParameterList;
    QryListaEntrEstoque: TFDQuery;
    QryListaEntrEstoquefornecedor: TWideStringField;
    QryListaEntrEstoquedataentradaestoque: TDateField;
    QryListaEntrEstoquenumeronf: TIntegerField;
    QryListaEntrEstoqueproduto: TWideStringField;
    QryListaEntrEstoquelocalestoque: TWideStringField;
    QryListaEntrEstoquecentrocusto: TWideStringField;
    QryListaEntrEstoquevalortotalnf: TFMTBCDField;
    QryListaEntrEstoqueqtditens: TFMTBCDField;
    QryListaEntrEstoqueunidademedida: TWideStringField;
    QryListaEntrEstoquepesoembalagem: TFMTBCDField;
    QryListaEntrEstoqueidlocalestoque: TIntegerField;
    QryListaEntrEstoquesyncaws: TIntegerField;
    QryListaEntrEstoquesyncfaz: TIntegerField;
    QryListaEntrEstoquetipo: TWideStringField;
    QryListaEntrEstoquevaloruni: TFMTBCDField;
    dsListaEntrEstoque: TDataSource;
    ppDBListaEntrEstoque: TppDBPipeline;
    ppRepListaEntrEstoque: TppReport;
    ppHeaderBand11: TppHeaderBand;
    ppLabel157: TppLabel;
    ppLine30: TppLine;
    ppImage10: TppImage;
    ppDetailBand11: TppDetailBand;
    ppLine31: TppLine;
    ppDBText125: TppDBText;
    ppDBText126: TppDBText;
    ppDBText127: TppDBText;
    ppDBText128: TppDBText;
    ppDBText129: TppDBText;
    ppDBText130: TppDBText;
    ppDBText124: TppDBText;
    ppDBText132: TppDBText;
    ppDBText133: TppDBText;
    ppDBText138: TppDBText;
    ppFooterBand11: TppFooterBand;
    ppSystemVariable21: TppSystemVariable;
    ppSystemVariable22: TppSystemVariable;
    ppSummaryBand11: TppSummaryBand;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppShape79: TppShape;
    ppLabel158: TppLabel;
    ppLabel160: TppLabel;
    ppLabel161: TppLabel;
    ppLabel162: TppLabel;
    ppLabel163: TppLabel;
    ppLabel164: TppLabel;
    ppShape80: TppShape;
    ppLabel165: TppLabel;
    ppDBText131: TppDBText;
    ppLabel159: TppLabel;
    ppLabel166: TppLabel;
    ppLabel167: TppLabel;
    ppLabel174: TppLabel;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppShape81: TppShape;
    ppDBCalc32: TppDBCalc;
    ppShape82: TppShape;
    ppDBCalc33: TppDBCalc;
    ppShape83: TppShape;
    ppDBCalc34: TppDBCalc;
    ppDesignLayers11: TppDesignLayers;
    ppDesignLayer11: TppDesignLayer;
    ppParameterList11: TppParameterList;
    QryListaSaidaEstoque: TFDQuery;
    QryListaSaidaEstoqueproduto: TWideStringField;
    QryListaSaidaEstoquecodigofabricante: TWideStringField;
    QryListaSaidaEstoquelocalestoque: TWideStringField;
    QryListaSaidaEstoquecentrocusto: TWideStringField;
    QryListaSaidaEstoquedatasaida: TDateField;
    QryListaSaidaEstoquetipo_baixa: TWideStringField;
    QryListaSaidaEstoqueunidademedida: TWideStringField;
    QryListaSaidaEstoqueqtde: TFMTBCDField;
    QryListaSaidaEstoquevalorunidade: TBCDField;
    QryListaSaidaEstoquevalortotal: TFMTBCDField;
    dsListaSaidaEstoque: TDataSource;
    ppDBPListaSaidaEstoque: TppDBPipeline;
    ppRepppListaSaidaEstoque: TppReport;
    ppHeaderBand12: TppHeaderBand;
    ppLabel168: TppLabel;
    ppLine32: TppLine;
    ppImage11: TppImage;
    ppShape84: TppShape;
    ppLabel169: TppLabel;
    ppLabel171: TppLabel;
    ppLabel172: TppLabel;
    ppLabel173: TppLabel;
    ppLabel176: TppLabel;
    ppLabel177: TppLabel;
    ppLabel178: TppLabel;
    ppLabel170: TppLabel;
    ppDetailBand12: TppDetailBand;
    ppLine33: TppLine;
    ppDBText135: TppDBText;
    ppDBText136: TppDBText;
    ppDBText137: TppDBText;
    ppDBText139: TppDBText;
    ppDBText140: TppDBText;
    ppDBText141: TppDBText;
    ppDBText142: TppDBText;
    ppDBText134: TppDBText;
    ppFooterBand12: TppFooterBand;
    ppSystemVariable23: TppSystemVariable;
    ppSystemVariable24: TppSystemVariable;
    ppSummaryBand12: TppSummaryBand;
    ppShape86: TppShape;
    ppDBCalc35: TppDBCalc;
    ppShape87: TppShape;
    ppDBCalc36: TppDBCalc;
    ppShape88: TppShape;
    ppDBCalc37: TppDBCalc;
    ppDesignLayers12: TppDesignLayers;
    ppDesignLayer12: TppDesignLayer;
    ppParameterList12: TppParameterList;
    procedure ppHeaderBand1BeforePrint(Sender: TObject);
    type
      StringArray = array of string;
      IntegerArray = array of integer;
      TCharSet = set of char;
  private
    { Private declarations }
  public
    vItem     :integer;
    vIdPedido :string;
    procedure GeraComparativo(idPedido:string);
    function  MenorValor(v1,v2,v3,v4,v5,v6 :Double): Double;
    function  MaiorValor(v1,v2,v3,v4,v5,v6 :Double): Double;
    function  split(const str: string; const delims: TCharSet): StringArray;
    function  SmallIntArray(Vetor: array of Double): Double;
    function  SmallIntArrayMaior(Vetor: array of Double): Double;
    procedure AbreQryComparativo(vIdPedido:string);
    procedure AbreExtratoCombustivel(idComb,NomeCOmb,DataIni,DataFim:string);
    procedure AbreExtratoBomba(idComb, NomeCOmb, DataIni,
     DataFim: string);
    procedure AbreSaldoAtualCombustivel(vFiltro:string);
    procedure AbreExtratoDiaMaquina(DataIni,DataFim,idLocal:string);
    procedure AbreRepNota(vIdNota:string);

    procedure SaldoAtualCustoMedio(vFiltro:string);
    procedure AbreListaEntradas(vFiltro:string);
    procedure AbreListaSaidas(vFiltro:string);
  end;

var
  dmReport: TdmReport;

implementation

{%CLASSGROUP 'FMX.Controls.TControl'}

uses DataContext, UdmReport;

{$R *.dfm}

procedure TdmReport.AbreExtratoCombustivel(idComb, NomeCOmb, DataIni,
  DataFim: string);
var
 vDataIni,vDataFim:string;
begin
 vDataIni  := FormatDateTime('yyyy-mm-dd',StrToDate(DataIni)).QuotedString;
 vDataFim  := FormatDateTime('yyyy-mm-dd',StrToDate(DataFim)).QuotedString;
 with ExtratoCombustivel,ExtratoCombustivel.sql do
 begin
   Clear;
   Add('select * from FExtratoCombustivel(');
   Add(vDataIni+',');
   Add(vDataFim+',');
   Add(idComb+')');
   Open;
   if not IsEmpty then
   begin
    ppLblCombustivel.Text := NomeComb;
    ppLblPeriodoComb.Text := 'De '+DataIni+' ate '+DataFim;
    ppReportExtratoComb.Print;
   end
   else
   begin
     ShowMessage('Sem dados para esse filtro!!');
   end;
 end;
end;

procedure TdmReport.AbreExtratoDiaMaquina(DataIni,DataFim,idLocal: string);
begin
 with qryAux,qryAux.SQL do
 begin
   Clear;
   Add('delete from extratoCombustivel');
   ExecSQL;
 end;
 dmRel.GeraExtratoCombustivel(DataIni,DataFim,idLocal);
 with ExtratoDiaMaquina,ExtratoDiaMaquina.sql do
 begin
   Clear;
   Add('select * from extratoCombustivel');
   Open;
   ppLblPeriodoEx.Text :=DataIni+' ate '+DataFim;
   ppRepExtratoMaquinaDia.Print;
 end;
end;

procedure TdmReport.AbreListaEntradas(vFiltro: string);
begin
 with QryListaEntrEstoque,QryListaEntrEstoque.SQL do
 begin
   Clear;
   Add('select');
   Add(' f.nome Fornecedor,');
   Add(' b.dataentradaestoque,');
   Add(' b.numeronf,');
   Add(' c.nome Produto,');
   Add(' d.nome LocalEstoque,');
   Add(' e.nome CentroCusto,');
   Add(' a.*,');
   Add(' a.valortotalnf/a.qtditens as  ValorUni,');
   Add('cast(case');
   Add(' when b.tipo =0 then ''COMPRA''');
   Add(' when b.tipo =1 then ''ACERTO''');
   Add('end as varchar(10))Tipo');
   Add('from notafiscalitems a');
   Add('join estoqueentrada b on a.idnota=b.id');
   Add('join produtos c on c.id=a.idproduto');
   Add('join localestoque d on d.id=a.idlocalestoque');
   Add('join centrocusto e on e.id=b.idcentrocusto');
   Add('join fornecedor f on f.id=b.idfornecedor');
   Add('where a.status=1');
   Add(vFiltro);
   Add('order by a.id desc');
   Open;
 end;
end;

procedure TdmReport.AbreListaSaidas(vFiltro: string);
begin
 with QryListaSaidaEstoque,QryListaSaidaEstoque.SQL do
 begin
   Clear;
   Add('select');
   Add(' c.nome Produto,');
   Add(' c.codigofabricante CodigoFabricante,');
   Add(' e.nome LocalEstoque,');
   Add(' d.nome CentroCusto,');
   Add(' a.datasaidaestoque DataSaida,');
   Add(' cast(case');
   Add('  when tipo_baixa=0 then ''CONSUMO''');
   Add('  when tipo_baixa=1 then ''ACERTO''');
   Add(' end as varchar(10)) tipo_baixa,');
   Add(' a.unidademedida,');
   Add(' a.qtditens Qtde,');
   Add(' a.valorsaida ValorUnidade,');
   Add(' a.valorsaida * a.qtditens  ValorTotal');
   Add('from estoquesaida a');
   Add('join produtos c on c.id=a.idproduto');
   Add('join localestoque d on d.id=a.idlocalestoque');
   Add('join centrocusto e on e.id=a.idcentrocusto');
   Add('where a.status =1');
   Add(vFiltro);
   Add('order by a.id desc');
   Open;
 end;
end;

procedure TdmReport.AbreExtratoBomba(idComb, NomeCOmb, DataIni,
  DataFim: string);
var
 vDataIni,vDataFim:string;
begin
 vDataIni  := FormatDateTime('yyyy-mm-dd',StrToDate(DataIni)).QuotedString;
 vDataFim  := FormatDateTime('yyyy-mm-dd',StrToDate(DataFim)).QuotedString;
 with ExtratoBomba,ExtratoBomba.sql do
 begin
   Clear;
   Add('select * from FExtratoLocal(');
   Add(vDataIni+',');
   Add(vDataFim+',');
   Add(idComb+')');
   Open;
   if not IsEmpty then
   begin
    LblBomba.Text := NomeComb;
    ppLblPeriodoBomba.Text := 'De '+DataIni+' ate '+DataFim;
    ppRepExtratoBomba.Print;
   end
   else
   begin
     ShowMessage('Sem dados para esse filtro!!');
   end;
 end;
end;

procedure TdmReport.AbreQryComparativo(vIdPedido: string);
begin
// with qryComparativo,qryComparativo.SQL do
// begin
//   Clear;
//   Add('rollback;');
//   Add('begin;');
//   Add('select colpivot(');
//   Add(QuotedStr('_test_pivoted')+',');
//   Add('''select');
//   Add('p.id Produto,');
//   Add('substring(f.nome from 0 for 20) Fornecedor,');
//   Add('sum(b.valorunidade)valorunidade');
//   Add('from orcamentos a');
//   Add('join fornecedor f on f.id=a.idfornecedor');
//   Add('join orcamentositens b on a.id=b.idorcamento');
//   Add('join produtos p on p.id=b.idproduto');
//   Add('where idpedido='+vIdPedido+' and a.status>-1');
//   Add('group by p.id,f.nome  order by p.nome'''+',');
//   Add('array[''produto''], array[''fornecedor''], ''#.valorunidade'', null);');
//   Add('select * from _test_pivoted');
//   Add('rollback;');
//   qryComparativo.SQL.Text;
//   Open;
// end;

 with qryDadosOrcamento,qryDadosOrcamento.SQL do
 begin
   Clear;
   Add('select * from orcamentositens a');
   Add('join produtos b on a.idproduto=b.id');
   Add('join orcamentos c on c.id=a.idorcamento');
   Add('where c.idpedido='+vIdPedido);
   Open;
 end;
end;

procedure TdmReport.AbreRepNota(vIdNota: string);
begin
 with qryImprimeNota,qryImprimeNota.SQL do
 begin
   Clear;
   Add('select');
   Add('f.nome Fornecedor,');
   Add('b.dataentradaestoque,');
   Add('b.numeronf,');
   Add('b.dataemissao,');
   Add('b.dataentradaestoque,');
   Add('ROW_NUMBER () OVER (ORDER BY a.id)Item,');
   Add('c.nome Produto,');
   Add('d.nome LocalEstoque,');
   Add('e.nome CentroCusto,');
   Add('a.*,');
   Add('a.valortotalnf/a.qtditens ValorUni,');
   Add('cast(case');
   Add('when b.tipo =0 then ''COMPRA''');
   Add('when b.tipo =1 then ''ACERTO''');
   Add('end as varchar(10))Tipo');
   Add('from notafiscalitems a');
   Add('join estoqueentrada b on a.idnota=b.id');
   Add('join produtos c on c.id=a.idproduto');
   Add('join localestoque d on d.id=a.idlocalestoque');
   Add('join centrocusto e on e.id=b.idcentrocusto');
   Add('join fornecedor f on f.id=b.idfornecedor');
   Add('WHERE b.ID='+vIdNota);
   Add('ORDER BY A.ID');
   Open;
   ppRepListaEntNotas.Print;
 end;
end;

procedure TdmReport.AbreSaldoAtualCombustivel(vFiltro: string);
begin
  with SaldoAtualCombustivel,SaldoAtualCombustivel.SQL do
  begin
    Clear;
    Add('select');
    Add(' entrada.localestoque,');
    Add(' coalesce(entrada.produto,saida.produto)produto,');
    Add(' coalesce(entrada.qtdEntrada,0) entradas,');
    Add(' coalesce(saida.qtdSaida,0)Saidas,');
    Add(' (coalesce(entrada.qtdEntrada,0)+coalesce(TOTAL_ENT_TRANS,0))-(coalesce(saida.qtdSaida,0)+coalesce(TRO.TOTAL_SAIDA_TRANS,0))saldo,');
    Add(' coalesce(TRO.TOTAL_SAIDA_TRANS,0)TOTAL_SAIDA_TRANS,');
    Add(' coalesce(TOTAL_ENT_TRANS,0)TOTAL_ENTRADA_TRANS');
    Add('from');
    Add('(');
    Add('select');
    Add(' a.id idlocalestoque,');
    Add(' b.id idProduto,');
    Add(' a.nome LocalEstoque,');
    Add(' b.nome Produto,');
    Add(' sum(c.qtditens) qtdEntrada');
    Add('from localestoque a');
    Add('left join estoqueentrada c on c.idlocalestoque=a.id');
    Add('left join produtos b on  c.idproduto=b.id');
    Add('group by a.id,b.id,a.nome,b.nome');
    Add(')entrada');
    Add('left join');
    Add('(');
    Add('select ab.idlocalestoque,p.id idProduto,nome produto,sum(ab.volumelt) qtdSaida from abastecimento ab');
    Add('join produtos p on p.id=ab.combustivel');
    Add('where ab.status=1');
    Add('group by ab.idlocalestoque,p.id,nome');
    Add(')saida');
    Add('on saida.idlocalestoque=entrada.idlocalestoque');
    Add('left join');
    Add('(select t.idlocalestoqueorigem,sum(t.qtde) TOTAL_SAIDA_TRANS from tranferencialocalestoque t');
    Add('where t.status=1');
    Add('group by t.idlocalestoqueorigem)TRO');
    Add('on TRO.idlocalestoqueorigem=entrada.idlocalestoque');
    Add('left join');
    Add('(select t.idlocalestoquedetino ,sum(t.qtde) TOTAL_ENT_TRANS from tranferencialocalestoque t');
    Add('where t.status=1');
    Add('group by t.idlocalestoquedetino )TRD');
    Add('on TRD.idlocalestoquedetino =entrada.idlocalestoque');
    Add('where 1=1');
    if vFiltro.Length>0 then
     Add(vFiltro);
    Open;
    if not isempty then
     ppRepSaldoAtual.Print
    else
     ShowMessage('sem dados para esse filtro');
  end;
end;

procedure TdmReport.GeraComparativo(idPedido: string);
var
 I:integer;
begin
  vItem     := 0;
  vIdPedido := idPedido;
  AbreQryComparativo(vIdPedido);
  ppRepComparativo.Print;
end;

function TdmReport.MaiorValor(v1, v2, v3, v4, v5, v6: Double): Double;
var
 vIn   : Double;
 Vetor : Array of double;
begin
 SetLength(Vetor, 6);
 vetor[0] := v1;
 vetor[1] := v2;
 vetor[2] := v3;
 vetor[3] := v4;
 vetor[4] := v5;
 vetor[5] := v6;
 result := SmallIntArrayMaior(Vetor);
end;

function TdmReport.MenorValor(v1,v2,v3,v4,v5,v6 :Double): Double;
var
 vIn   : Double;
 Vetor : Array of double;
begin
 SetLength(Vetor, 6);
 vetor[0] := v1;
 vetor[1] := v2;
 vetor[2] := v3;
 vetor[3] := v4;
 vetor[4] := v5;
 vetor[5] := v6;
 result := SmallIntArray(Vetor);
end;

procedure TdmReport.ppHeaderBand1BeforePrint(Sender: TObject);
begin
 if dbCtx.TPedidoCompraRepidmaquina.AsString.Length >0 then
 begin
   ppLblTipoMaquina.Caption   := 'Maquina:';
   ppDBLBLServico.Visible     := false;
   ppDBLBLMaquina.Visible     := true;
   pplblDescricao.Visible     := false;
   ppDescricaoServico.Visible := false;
 end;
 if dbCtx.TPedidoCompraRepidservico.AsString.Length >0 then
 begin
   ppLblTipoMaquina.Caption   := 'Serviço:';
   ppDBLBLServico.Visible     := true;
   ppDBLBLMaquina.Visible     := false;
   pplblDescricao.Visible     := true;
   ppDescricaoServico.Visible := true;
 end;
 if (dbCtx.TPedidoCompraRepidservico.AsString.Length=0) and
  (dbCtx.TPedidoCompraRepidmaquina.AsString.Length=0) then
 begin
   ppLblTipoMaquina.Caption   := 'Produtos Estoque';
   ppDBLBLServico.Visible     := false;
   ppDBLBLMaquina.Visible     := false;
   pplblDescricao.Visible     := false;
   ppDescricaoServico.Visible := false;
 end;
end;

procedure TdmReport.SaldoAtualCustoMedio(vFiltro: string);
begin
 with QryEstoqueG,QryEstoqueG.SQL do
 begin
   Clear;
   Add('select');
   Add('a.nome,');
   Add('a.codigofabricante,');
   Add('(select coalesce(sum(qtditens),0) from notafiscalitems n');
   Add('where n.status=1 and n.idproduto=a.id) TotalEntradas,');
   Add('(select coalesce(sum(ss.qtditens),0) from estoquesaida ss');
   Add('where ss.status=1 and ss.idproduto=a.id) TotalSaida,');
   Add('a.saldoatual,');
   Add('a.customedio,');
   Add('(select max(dataentradaestoque) from notafiscalitems n');
   Add('join estoqueentrada c on c.id=n.idnota');
   Add('where n.idproduto=a.id) UltimaEntrada,');
   Add('(select max(ss.datasaidaestoque)  from estoquesaida ss');
   Add('where ss.idproduto=a.id) UltimaSaida');
   Add('from produtos  a');
   Add('where a.saldoatual is not null');
   Add(vFiltro);
   Open;
 end;
end;

function TdmReport.SmallIntArray(Vetor: array of Double): Double;
var
   I: Integer;
begin
 Result:= 0;
 for I:= 0 to Length(Vetor) - 1 do
     begin
      if Result = 0 then
         Result:= Vetor[I];
      if Vetor[I] > 0 then
         if Vetor[I] < Result then
            Result:= Vetor[I];
     end;
end;

function TdmReport.SmallIntArrayMaior(Vetor: array of Double): Double;
var
   I: Integer;
begin
 Result:= 0;
 for I:= 0 to Length(Vetor) - 1 do
     begin
      if Result = 0 then
         Result:= Vetor[I];
      if Vetor[I] > 0 then
         if Vetor[I] > Result then
            Result:= Vetor[I];
     end;
end;

function TdmReport.split(const str: string;
  const delims: TCharSet): StringArray;
var
  SepPos: IntegerArray;
  i: Integer;
begin
  SetLength(SepPos, 1);
  SepPos[0] := 0;
  for i := 1 to length(str) do
    if str[i] in delims then
    begin
      SetLength(SepPos, length(SepPos) + 1);
      SepPos[high(SepPos)] := i;
    end;
  SetLength(SepPos, length(SepPos) + 1);
  SepPos[high(SepPos)] := length(str) + 1;
  SetLength(result, high(SepPos));
  for i := 0 to high(SepPos) -  1 do
    result[i] := Trim(Copy(str, SepPos[i] + 1, SepPos[i+1] - SepPos[i] - 1));
end;

end.
