unit UdmCompras;

interface

uses
  System.SysUtils, System.Classes, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Param, FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf,
  FireDAC.DApt.Intf, FireDAC.Stan.Async, FireDAC.DApt, Data.DB,
  FireDAC.Comp.DataSet, FireDAC.Comp.Client, ppParameter, ppDesignLayer,
  ppCtrls, ppBands, ppVar, Vcl.Imaging.jpeg, ppStrtch, ppMemo, ppPrnabl,
  ppClass, ppCache, ppProd, ppReport, ppDB, ppComm, ppRelatv, ppDBPipe;

type
  TdmCompras = class(TDataModule)
    AuxFormaPG: TFDQuery;
    AuxFormaPGid: TIntegerField;
    AuxFormaPGstatus: TIntegerField;
    AuxFormaPGdatareg: TSQLTimeStampField;
    AuxFormaPGidusuario: TIntegerField;
    AuxFormaPGdataalteracao: TSQLTimeStampField;
    AuxFormaPGidusuarioalteracao: TIntegerField;
    AuxFormaPGcodigo: TWideStringField;
    AuxFormaPGdescricao: TWideStringField;
    AuxFormaPGsyncfaz: TIntegerField;
    AuxFormaPGsyncaws: TIntegerField;
    TOrcamento: TFDQuery;
    TItensOrcamento: TFDQuery;
    TItensOrcamentoitem: TLargeintField;
    TItensOrcamentoid: TIntegerField;
    TItensOrcamentostatus: TIntegerField;
    TItensOrcamentodatareg: TSQLTimeStampField;
    TItensOrcamentoidusuario: TIntegerField;
    TItensOrcamentodataalteracao: TSQLTimeStampField;
    TItensOrcamentoidusuarioalteracao: TIntegerField;
    TItensOrcamentoidorcamento: TIntegerField;
    TItensOrcamentoidproduto: TIntegerField;
    TItensOrcamentovalorunidade: TBCDField;
    TItensOrcamentoobservacao: TWideStringField;
    TItensOrcamentosyncaws: TIntegerField;
    TItensOrcamentosyncfaz: TIntegerField;
    TItensOrcamentodesconto: TFMTBCDField;
    TItensOrcamentodescontogeral: TFMTBCDField;
    TItensOrcamentofretegeral: TFMTBCDField;
    TItensOrcamentoipi: TFMTBCDField;
    TItensOrcamentoicmst: TFMTBCDField;
    TItensOrcamentofrete: TFMTBCDField;
    TItensOrcamentodiferencialalicota: TFMTBCDField;
    TItensOrcamentomarca: TWideStringField;
    TItensOrcamentoidmarca: TIntegerField;
    TItensOrcamentooriginal: TIntegerField;
    TItensOrcamentounidademedida: TWideMemoField;
    TItensOrcamentoimg: TBlobField;
    TItensOrcamentoidentificadorpedido: TWideStringField;
    TItensOrcamentodatapedido: TDateField;
    TItensOrcamentostatuspedido: TIntegerField;
    TItensOrcamentonomefornecedor: TWideStringField;
    TItensOrcamentotelefonefornecedor: TWideStringField;
    TItensOrcamentoemailfornecedor: TWideStringField;
    TItensOrcamentocpfcnpjfornecedor: TWideStringField;
    TItensOrcamentonomeproduto: TWideStringField;
    TItensOrcamentocodfabproduto: TWideStringField;
    TItensOrcamentovalortotal: TBCDField;
    TItensOrcamentooriginalstr: TWideMemoField;
    TItensOrcamentoformapg: TWideMemoField;
    TItensOrcamentoidformapg: TIntegerField;
    TItensOrcamentofornecedor: TWideStringField;
    TItensOrcamentomarcanome: TWideStringField;
    TItensOrcamentodescontoitem: TFMTBCDField;
    TItensOrcamentofreteitem: TFMTBCDField;
    TItensOrcamentorecebido: TIntegerField;
    TItensOrcamentoobsrecebimento: TWideStringField;
    TItensOrcamentoqtdrecebida: TFMTBCDField;
    TItensOrcamentoresponsavelrecebimento: TIntegerField;
    TItensOrcamentodatarecebimento: TDateField;
    TItensOrcamentovalorbrutomaisfrete: TFMTBCDField;
    TItensOrcamentovalorliquido: TFMTBCDField;
    TItensOrcamentoqtde: TBCDField;
    ppDBOrcamento: TppDBPipeline;
    ppRepOrcamento: TppReport;
    ppHeaderBand2: TppHeaderBand;
    ppShape3: TppShape;
    ppLabel18: TppLabel;
    ppShape6: TppShape;
    ppLblOrdemPedido: TppLabel;
    ppShape4: TppShape;
    ppLabel13: TppLabel;
    ppDBText5: TppDBText;
    ppLabel15: TppLabel;
    ppDBText11: TppDBText;
    ppLabel16: TppLabel;
    ppDBText12: TppDBText;
    ppLabel17: TppLabel;
    ppDBMemo2: TppDBMemo;
    ppLabel19: TppLabel;
    ppDBMemo5: TppDBMemo;
    ppLabel20: TppLabel;
    ppLine4: TppLine;
    ppLabel21: TppLabel;
    ppLabel22: TppLabel;
    ppLabel24: TppLabel;
    ppDBText14: TppDBText;
    ppLabel26: TppLabel;
    ppLabel25: TppLabel;
    ppLabel31: TppLabel;
    ppDBMemo6: TppDBMemo;
    ppLabel35: TppLabel;
    ppDBText21: TppDBText;
    ppLabel36: TppLabel;
    ppDBText22: TppDBText;
    ppLabel37: TppLabel;
    ppDBText23: TppDBText;
    ppLabel11: TppLabel;
    ppLabel29: TppLabel;
    ppLabel87: TppLabel;
    ppLabel89: TppLabel;
    ppLabel205: TppLabel;
    ppLabel206: TppLabel;
    ppLabel207: TppLabel;
    ppLabel208: TppLabel;
    ppLabel209: TppLabel;
    ppLabel211: TppLabel;
    ppLabel212: TppLabel;
    ppDBText171: TppDBText;
    ppDBText59: TppDBText;
    ppImage8: TppImage;
    ppDetailBand2: TppDetailBand;
    ppDBText13: TppDBText;
    ppDBText17: TppDBText;
    ppDBText18: TppDBText;
    ppDBText19: TppDBText;
    ppLine5: TppLine;
    ppDBText20: TppDBText;
    ppDBText60: TppDBText;
    ppDBText16: TppDBText;
    ppDBText24: TppDBText;
    ppDBText166: TppDBText;
    ppDBText167: TppDBText;
    ppDBText168: TppDBText;
    ppDBText169: TppDBText;
    ppDBText170: TppDBText;
    ppDBText58: TppDBText;
    ppDBText15: TppDBText;
    ppFooterBand2: TppFooterBand;
    ppSystemVariable3: TppSystemVariable;
    ppSystemVariable4: TppSystemVariable;
    ppLine6: TppLine;
    ppSummaryBand2: TppSummaryBand;
    ppShape5: TppShape;
    ppDBCalc3: TppDBCalc;
    ppLabel23: TppLabel;
    ppLabel27: TppLabel;
    ppLabel28: TppLabel;
    ppDBCalc5: TppDBCalc;
    ppLabel88: TppLabel;
    ppDBCalc43: TppDBCalc;
    ppLabel210: TppLabel;
    ppDBCalc44: TppDBCalc;
    ppDBCalc2: TppDBCalc;
    ppDesignLayers2: TppDesignLayers;
    ppDesignLayer2: TppDesignLayer;
    ppParameterList2: TppParameterList;
    ppDBItensOrcamento: TppDBPipeline;
    ppRepOrdemCompra: TppReport;
    ppHeaderBand9: TppHeaderBand;
    ppShape31: TppShape;
    ppLabel129: TppLabel;
    ppShape32: TppShape;
    ppLabel130: TppLabel;
    ppShape33: TppShape;
    ppLabel131: TppLabel;
    ppDBText110: TppDBText;
    ppLabel138: TppLabel;
    ppDBText111: TppDBText;
    ppLabel139: TppLabel;
    ppDBText112: TppDBText;
    ppLabel140: TppLabel;
    ppDBMemo9: TppDBMemo;
    ppLabel141: TppLabel;
    ppDBMemo10: TppDBMemo;
    ppLabel142: TppLabel;
    ppLine25: TppLine;
    ppLabel143: TppLabel;
    ppLabel144: TppLabel;
    ppLabel145: TppLabel;
    ppDBText113: TppDBText;
    ppLabel146: TppLabel;
    ppLabel147: TppLabel;
    ppLabel148: TppLabel;
    ppDBMemo11: TppDBMemo;
    ppLabel179: TppLabel;
    ppDBText115: TppDBText;
    ppLabel180: TppLabel;
    ppDBText116: TppDBText;
    ppLabel197: TppLabel;
    ppLabel198: TppLabel;
    ppLabel199: TppLabel;
    ppLabel200: TppLabel;
    ppLabel201: TppLabel;
    ppLabel202: TppLabel;
    ppLabel203: TppLabel;
    ppLabel204: TppLabel;
    ppLabel213: TppLabel;
    ppLabel214: TppLabel;
    ppLabel215: TppLabel;
    ppDBText143: TppDBText;
    ppDBText147: TppDBText;
    ppShape70: TppShape;
    ppLabel221: TppLabel;
    ppLabel222: TppLabel;
    ppLabel223: TppLabel;
    ppLabel224: TppLabel;
    ppLabel225: TppLabel;
    ppLabel226: TppLabel;
    ppLabel227: TppLabel;
    ppLabel228: TppLabel;
    ppLabel229: TppLabel;
    ppLabel230: TppLabel;
    ppDBText178: TppDBText;
    ppDBText179: TppDBText;
    ppDBText180: TppDBText;
    ppDBText181: TppDBText;
    ppLabel231: TppLabel;
    ppDBText182: TppDBText;
    ppDBText183: TppDBText;
    ppDBText184: TppDBText;
    ppDBText185: TppDBText;
    ppDBText186: TppDBText;
    ppDBText114: TppDBText;
    ppImage13: TppImage;
    ppLabel265: TppLabel;
    ppDBText206: TppDBText;
    ppLabel266: TppLabel;
    ppLabel267: TppLabel;
    ppDBText207: TppDBText;
    ppDBText208: TppDBText;
    ppDetailBand9: TppDetailBand;
    ppDBText151: TppDBText;
    ppDBText158: TppDBText;
    ppDBText159: TppDBText;
    ppDBText160: TppDBText;
    ppDBText161: TppDBText;
    ppLine26: TppLine;
    ppDBText162: TppDBText;
    ppDBText163: TppDBText;
    ppDBText164: TppDBText;
    ppDBText165: TppDBText;
    ppDBText172: TppDBText;
    ppDBText173: TppDBText;
    ppDBText174: TppDBText;
    ppDBText175: TppDBText;
    ppDBText176: TppDBText;
    ppDBText177: TppDBText;
    ppFooterBand9: TppFooterBand;
    ppSystemVariable17: TppSystemVariable;
    ppSystemVariable18: TppSystemVariable;
    ppLine27: TppLine;
    ppSummaryBand9: TppSummaryBand;
    ppShape69: TppShape;
    ppDBCalc6: TppDBCalc;
    ppDBCalc41: TppDBCalc;
    ppLabel216: TppLabel;
    ppLabel217: TppLabel;
    ppLabel218: TppLabel;
    ppDBCalc42: TppDBCalc;
    ppLabel219: TppLabel;
    ppDBCalc45: TppDBCalc;
    ppLabel220: TppLabel;
    ppDBCalc46: TppDBCalc;
    ppDesignLayers9: TppDesignLayers;
    ppDesignLayer9: TppDesignLayer;
    ppParameterList9: TppParameterList;
    dsOrcamento: TDataSource;
    dsOrcamentoItens: TDataSource;
    ppDBPedidoProduto: TppDBPipeline;
    ppRepPedidoProduto: TppReport;
    ppHeaderBand1: TppHeaderBand;
    ppLabel2: TppLabel;
    ppDetailBand1: TppDetailBand;
    ppDBText25: TppDBText;
    ppDBText27: TppDBText;
    ppLine2: TppLine;
    ppFooterBand1: TppFooterBand;
    ppSystemVariable1: TppSystemVariable;
    ppSystemVariable2: TppSystemVariable;
    ppLine3: TppLine;
    ppSummaryBand1: TppSummaryBand;
    ppDesignLayers1: TppDesignLayers;
    ppDesignLayer1: TppDesignLayer;
    ppParameterList1: TppParameterList;
    ppDBText8: TppDBText;
    ppDBText9: TppDBText;
    TOrcamentoid: TIntegerField;
    TOrcamentostatus: TIntegerField;
    TOrcamentodatareg: TSQLTimeStampField;
    TOrcamentoidusuario: TIntegerField;
    TOrcamentodataalteracao: TSQLTimeStampField;
    TOrcamentoidusuarioalteracao: TIntegerField;
    TOrcamentoidfornecedor: TIntegerField;
    TOrcamentoidpedido: TIntegerField;
    TOrcamentoobservacao: TWideStringField;
    TOrcamentosyncaws: TIntegerField;
    TOrcamentosyncfaz: TIntegerField;
    TOrcamentodesconto: TBCDField;
    TOrcamentoipi: TBCDField;
    TOrcamentoicmst: TBCDField;
    TOrcamentofrete: TBCDField;
    TOrcamentodiferencialalicota: TBCDField;
    TOrcamentoidformapagamento: TIntegerField;
    TOrcamentodataprevitaentrega: TDateField;
    TOrcamentodatacompra: TDateField;
    TOrcamentoresponsavelcompra: TWideStringField;
    TOrcamentostatusstr: TWideMemoField;
    TOrcamentoidentificador: TWideStringField;
    TOrcamentodatapedido: TDateField;
    TOrcamentofornecedor: TWideStringField;
    TOrcamentoemail: TWideStringField;
    TOrcamentosenha: TWideStringField;
    TOrcamentocpf_cnpj: TWideStringField;
    TOrcamentotelefone_fixo: TWideStringField;
    TOrcamentoinscricaoestadual: TWideStringField;
    TOrcamentocidade: TWideStringField;
    TOrcamentocontatopessoa: TWideStringField;
    TOrcamentoformapg: TWideMemoField;
    TOrcamentovalortotal: TFMTBCDField;
    TOrcamentoitemfrete: TFMTBCDField;
    TOrcamentoitemdesconto: TFMTBCDField;
    TOrcamentoitemicmst: TFMTBCDField;
    TOrcamentoitemipi: TFMTBCDField;
    TOrcamentoitemdifal: TFMTBCDField;
    TOrcamentoresponsavelcompra_1: TWideStringField;
    TOrcamentodataprevitaentrega_1: TDateField;
    TOrcamentoproduto: TWideStringField;
    TOrcamentocodfabricante: TWideStringField;
    TOrcamentovalorunidade: TBCDField;
    TOrcamentovalortotalproduto: TBCDField;
    TOrcamentoipiproduto: TBCDField;
    TOrcamentoicmstproduto: TBCDField;
    TOrcamentodiferencialalicotaproduto: TBCDField;
    TOrcamentosolicitante: TWideStringField;
    TOrcamentoresponsavelordemcompra: TWideStringField;
    TOrcamentoqtdsolicitada: TFMTBCDField;
    TOrcamentoqtdecompra: TBCDField;
    TOrcamentodatacompra_1: TSQLTimeStampField;
    TOrcamentodiascompra: TIntegerField;
    TOrcamentovalorliquido: TFMTBCDField;
    ppShape1: TppShape;
    ppLabel9: TppLabel;
    ppLabel30: TppLabel;
    ppLabel10: TppLabel;
    ppLabel12: TppLabel;
    ppLabel14: TppLabel;
    ppDBText26: TppDBText;
    ppLabel1: TppLabel;
    ppDBText1: TppDBText;
    ppLabel3: TppLabel;
    ppDBCalc1: TppDBCalc;
    ppLabel4: TppLabel;
    ppDBCalc4: TppDBCalc;
    ppLabel5: TppLabel;
    ppDBCalc7: TppDBCalc;
    ppRepFornecedor: TppReport;
    ppHeaderBand3: TppHeaderBand;
    ppLabel7: TppLabel;
    ppLine1: TppLine;
    ppImage1: TppImage;
    ppDetailBand3: TppDetailBand;
    ppFooterBand3: TppFooterBand;
    ppSystemVariable5: TppSystemVariable;
    ppSystemVariable6: TppSystemVariable;
    ppLine8: TppLine;
    ppSummaryBand3: TppSummaryBand;
    ppDesignLayers3: TppDesignLayers;
    ppDesignLayer3: TppDesignLayer;
    ppParameterList3: TppParameterList;
    ppGroup1: TppGroup;
    ppGroupHeaderBand1: TppGroupHeaderBand;
    ppGroupFooterBand1: TppGroupFooterBand;
    ppShape2: TppShape;
    ppShape8: TppShape;
    ppLabel33: TppLabel;
    ppDBText4: TppDBText;
    ppLabel6: TppLabel;
    ppDBText6: TppDBText;
    ppLabel34: TppLabel;
    ppLabel38: TppLabel;
    ppLabel39: TppLabel;
    ppDBText7: TppDBText;
    ppDBText10: TppDBText;
    ppDBText28: TppDBText;
    ppLine7: TppLine;
    ppDBCalc8: TppDBCalc;
    ppShape7: TppShape;
    ppLabel8: TppLabel;
    ppLabel32: TppLabel;
    ppDBText2: TppDBText;
    ppDBText3: TppDBText;
    ppShape9: TppShape;
    ppDBCalc9: TppDBCalc;
    qryResumoGeral: TFDQuery;
    qryResumoGeralprimeiracompra: TDateField;
    qryResumoGeralultimacompra: TDateField;
    qryResumoGeraltotalpedidos: TLargeintField;
    qryResumoGeraltotalitens: TFMTBCDField;
    qryResumoGeralvalortotal: TFMTBCDField;
    qryResumoGeraldiasmedio: TFMTBCDField;
    dsResumo: TDataSource;
    ppDBPResumo: TppDBPipeline;
    ppRepResumo: TppReport;
    ppHeaderBand4: TppHeaderBand;
    ppLabel40: TppLabel;
    ppDetailBand4: TppDetailBand;
    ppFooterBand4: TppFooterBand;
    ppSystemVariable7: TppSystemVariable;
    ppSystemVariable8: TppSystemVariable;
    ppLine10: TppLine;
    ppSummaryBand4: TppSummaryBand;
    ppDesignLayers4: TppDesignLayers;
    ppDesignLayer4: TppDesignLayer;
    ppParameterList4: TppParameterList;
    ppImage2: TppImage;
    ppImage3: TppImage;
    ppShape10: TppShape;
    ppLabel41: TppLabel;
    ppDBText29: TppDBText;
    ppShape11: TppShape;
    ppLabel42: TppLabel;
    ppDBText30: TppDBText;
    ppShape12: TppShape;
    ppLabel43: TppLabel;
    ppDBText31: TppDBText;
    ppShape13: TppShape;
    ppLabel44: TppLabel;
    ppDBText32: TppDBText;
    ppShape14: TppShape;
    ppLabel45: TppLabel;
    ppDBText33: TppDBText;
    ppShape15: TppShape;
    ppLabel46: TppLabel;
    ppDBText34: TppDBText;
    ppLine9: TppLine;
  private
    { Private declarations }
  public
    procedure AbreFormaPagamento();
    procedure AbreOrcamentosLista(vFiltro: string);
    procedure AbreItemsOrcamentos(vFiltro: string);
    procedure AbreResumoGeralPedidos(vFiltro:string);
  end;

var
  dmCompras: TdmCompras;

implementation

{%CLASSGROUP 'FMX.Controls.TControl'}

uses DataContext;

{$R *.dfm}

{ TdmCompras }

procedure TdmCompras.AbreFormaPagamento();
begin
 with AuxFormaPG,AuxFormaPG.SQL do
 begin
   Clear;
   Add('select * from forma_pagamento_fornecedor');
   Add('where status=1');
   Open;
 end;
end;

procedure TdmCompras.AbreOrcamentosLista(vFiltro: string);
begin
 with TOrcamento,TOrcamento.SQL do
 begin
   Clear;
   Add('select y.*,((valortotal+itemfrete+itemipi+itemicmst+Itemdifal)-Itemdesconto)ValorLiquido from');
   Add('(select');
   Add('b.*,');
   Add('case');
   Add(' when b.status=1 then ''Solicitação''');
   Add(' when b.status=2 then ''Solicitação''');
   Add(' when b.status=3 then ''Ordem de Compra''');
   Add('end statusStr,');
   Add('c.identificador,');
   Add('c.datapedido,');
   Add('f.nome Fornecedor,');
   Add('f.email,');
   Add('f.senha,');
   Add('f.cpf_cnpj,');
   Add('f.telefone_fixo,');
   Add('f.inscricaoestadual,');
   Add('f.cidade,');
   Add('f.contatopessoa,');
   Add('fp.codigo||''-''||fp.descricao formapg,');
   Add('coalesce((select sum(valortotal) from orcamentositens where status=1 and idorcamento=b.id),0) valorTotal,');
   Add('coalesce(b.frete,(select sum(frete) from orcamentositens where status=1 and idorcamento=b.id),0) Itemfrete,');
   Add('coalesce(b.desconto,(select sum(desconto) from orcamentositens where status=1 and idorcamento=b.id),0)Itemdesconto,');
   Add('coalesce((select sum(icmst) from orcamentositens where status=1 and idorcamento=b.id),0)Itemicmst,');
   Add('coalesce((select sum(ipi) from orcamentositens where status=1 and idorcamento=b.id),0)Itemipi,');
   Add('coalesce((select sum(diferencialalicota) from orcamentositens where status=1 and idorcamento=b.id),0)Itemdifal,');
   Add('b.responsavelcompra,');
   Add('b.dataprevitaentrega,');
   Add('coalesce(b.datacompra,b.datareg)datacompra,');
   Add('coalesce(b.datacompra,cast(b.datareg as date))-c.datapedido diasCompra,');
   Add('p.nome Produto,');
   Add('o.valorunidade,');
   Add('o.valortotal ValorTotalProduto,');
   Add('o.ipi ipiProduto,');
   Add('o.icmst icmstProduto,');
   Add('o.diferencialalicota diferencialalicotaProduto,');
   Add('p.codigofabricante CodFabricante,');
   Add('u.nome solicitante,');
   Add('ud.nome ResponsavelOrdemCompra,');
   Add('(select p2.quantidade from pedidocompraitems p2 where p2.status>-1 and');
   Add('p2.idpedido=c.id and p2.iditem=p.id limit 1) QtdSolicitada,');
   Add('o.qtde QtdeCompra');
   Add('from orcamentos b');
   Add('join pedidocompra c on c.id=b.idpedido');
   Add('join usuario u on u.id=c.idsolicitante');
   Add('join usuario ud on ud.id=b.idusuario');
   Add('join fornecedor f on f.id=b.idfornecedor');
   Add('left join forma_pagamento_fornecedor fp on fp.id=b.idformapagamento');
   Add('join orcamentositens o on b.id=o.idorcamento');
   Add('join produtos p on o.idproduto=p.id');
   Add('where b.status>-1');
   Add(vFiltro);
   Add(')y');
   Open;
 end;
end;

procedure TdmCompras.AbreResumoGeralPedidos(vFiltro: string);
begin
 with qryResumoGeral,qryResumoGeral.SQL do
 begin
   Clear;
   Add('select');
   Add(' min(datacompra) PrimeiraCompra,');
   Add(' max(datacompra) UltimaCompra,');
   Add(' count(*) TotalPedidos,');
   Add(' avg(TotalItens) TotalItens,');
   Add(' avg(valortotal) ValorTotal,');
   Add(' avg(Dias)DiasMedio');
   Add('from');
   Add('(select');
   Add(' coalesce(o.datacompra,cast(o.datareg as date)) dataCompra,');
   Add(' p.id,');
   Add(' coalesce(o.datacompra,cast(o.datareg as date))-p.datapedido Dias,');
   Add(' (select');
   Add('  count(*)');
   Add(' from pedidocompra p');
   Add(' join orcamentos o  on o.idpedido =p.id and o.status =3');
   Add(' join orcamentositens o2 on o2.idorcamento=o.id');
   Add(' where p.status >-1 '+vFiltro+')TotalItens,');
   Add(' (select');
   Add('  sum(o2.valortotal)');
   Add(' from pedidocompra p');
   Add(' join orcamentos o  on o.idpedido =p.id and o.status =3');
   Add(' join orcamentositens o2 on o2.idorcamento=o.id');
   Add(' where p.status >-1)ValorTotal');
   Add('from pedidocompra p');
   Add('join orcamentos o  on o.idpedido =p.id and o.status =3');
   Add('where p.status >-1');
   Add(vFiltro);
   Add(')y');
   Open;
   ppRepResumo.Print;
 end;
end;

procedure TdmCompras.AbreItemsOrcamentos(vFiltro: string);
begin
 with TItensOrcamento,TItensOrcamento.SQL do
 begin
   Clear;
   Add('select y.*,');
   Add('y.valorTotal+coalesce(nullif(y.frete,0),y.freteItem) valorBrutoMaisFrete,');
   Add('y.valortotal+');
   Add('coalesce(nullif(y.frete,0),y.freteItem)+');
   Add('coalesce(y.ipi,0)+');
   Add('coalesce(y.icmst,0)+');
   Add('coalesce(y.diferencialalicota,0)-');
   Add('coalesce(nullif(y.desconto,0),y.descontoitem)valorLiquido');
   Add('from');
   Add('(select');
   Add('ROW_NUMBER () OVER (ORDER BY a.id)Item ,');
   Add(' a.id,a.status,a.datareg,a.idusuario,');
   Add(' a.dataalteracao,a.idusuarioalteracao,');
   Add(' a.idorcamento,a.idproduto,a.valorunidade,');
   Add(' a.observacao,a.qtde,a.syncaws,');
   Add(' a.syncfaz,');
   Add(' coalesce(nullif(b.desconto/');
   Add(' (select count(*) from orcamentositens o where o.idorcamento=b.id and status>-1),0),nullif(a.desconto,0))desconto,');
   Add('coalesce(nullif(b.desconto,0),');
   Add(' (select sum(coalesce(desconto,0))');
   Add('  from orcamentositens where status>-1 and idorcamento=b.id),0)DescontoGeral,');
   Add('coalesce(nullif(b.frete,0),');
   Add(' (select sum(coalesce(frete,0))');
   Add('  from orcamentositens where status>-1 and idorcamento=b.id),0)FreteGeral,');
   Add(' coalesce(a.ipi,0)ipi,');
   Add(' coalesce(a.icmst,0)icmst,');
   Add(' coalesce(nullif(b.frete/(');
   Add(' select count(*) from orcamentositens o where o.idorcamento=b.id and status>-1),0),nullif(a.frete,0))frete,');
   Add(' coalesce(a.diferencialalicota,0)diferencialalicota,');
   Add(' a.marca,');
   Add(' a.idmarca,');
   Add(' a.original,');
   Add(' a.unidademedida,');
   Add(' a.img,');
   Add(' c.identificador identificadorPedido,');
   Add(' c.datapedido DataPedido,');
   Add(' c.status StatusPedido,');
   Add(' d.nome NomeFornecedor,');
   Add(' d.telefone_fixo TelefoneFornecedor,');
   Add(' d.email EmailFornecedor,');
   Add(' d.cpf_cnpj CpfCnpjFornecedor,');
   Add(' e.Nome NomeProduto,');
   Add(' e.codigofabricante CodFabProduto,');
   Add(' e.unidademedida,');
   Add(' a.valortotal,');
   Add(' case');
   Add('   when original=1 then ''ORIGINAL''');
   Add('   when original=0 then ''PARALELO''');
   Add(' end originalStr,');
   Add(' fpf.codigo||''-''||fpf.descricao FormaPG,');
   Add(' fpf.id idFormaPg,');
   Add(' d.nome Fornecedor,');
   Add(' am.nome marcanome,');
   Add(' coalesce(a.desconto,0)descontoItem,');
   Add(' coalesce(a.frete,0)freteItem,');
   Add(' a.recebido ,');
   Add(' a.obsrecebimento,');
   Add(' qtdrecebida,');
   Add(' a.responsavelrecebimento,');
   Add(' datarecebimento');
   Add('from public.orcamentosItens a');
   Add('join orcamentos b on   b.id=a.idorcamento');
   Add('left join forma_pagamento_fornecedor fpf on fpf.id=b.idformapagamento');
   Add('join pedidocompra c on c.id=b.idpedido');
   Add('join fornecedor d on   d.id=b.idfornecedor');
   Add('join produtos e on      e.Id=a.idproduto');
   Add('left join auxmarcas am on am.id=a.idmarca');
   Add('where b.status>-1 and a.status>-1');
   Add('and idorcamento='+vFiltro);
   Add('order by Item');
   Add(')y');
   Open;
 end;
end;



end.
